### ユーザー情報取得
GET http://localhost:8000/api/users/1

### ユーザー情報取得
GET http://localhost:8000/api/users/index
Accept: application/json
Authorization: Bearer 1|lORWqXz8ZsLd3d1yidd4uDoQEpaPivXFoqwnwFPUc0cc534a

### ユーザー登録
POST http://localhost:8000/api/users/store
Content-Type: application/json
Accept: application/json

{
    "name": "kaya"
}

### ユーザー更新
POST http://localhost:8000/api/users/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|ycAmrbmCvTCfEs9kcMlgBKEdJcnQKzJ4b1UsNwJG23aff1ce

{
    "name": "kaya"
}

### フィールドデータ取得
GET http://localhost:8000/api/fields/2
